# Generated by Django 4.1.3 on 2022-11-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='url1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='url2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppApp.registration'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.CharField(max_length=20)),
                ('url2', models.CharField(max_length=20)),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppApp.requirements')),
            ],
        ),
    ]
