# Generated by Django 4.1.3 on 2023-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0004_remove_registration_age_remove_registration_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='product',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='url2',
        ),
        migrations.AddField(
            model_name='response',
            name='desc1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='desc2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='rate1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='rate2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='url1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='url2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
