# Generated by Django 4.1.3 on 2023-02-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='newRate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
