# Generated by Django 4.1.1 on 2023-04-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0007_wishlist_newrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='img1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='img2',
            field=models.URLField(null=True),
        ),
    ]
