# Generated by Django 4.1.3 on 2023-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0008_response_img1_response_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='offer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
