# Generated by Django 4.2 on 2023-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0009_wishlist_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='desc3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='img3',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='rate3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='url3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
