# Generated by Django 4.1.3 on 2023-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0010_response_desc3_response_img3_response_rate3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20, null=True)),
                ('img', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
