# Generated by Django 4.1.3 on 2023-05-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0011_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
