# Generated by Django 4.1.3 on 2023-05-18 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0012_remove_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppApp.products'),
        ),
    ]
