# Generated by Django 4.1.3 on 2023-05-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0013_requirements_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Rat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pRev',
            field=models.IntegerField(null=True),
        ),
    ]
