# Generated by Django 4.1.3 on 2023-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0015_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Rat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pRev',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
