# Generated by Django 4.1.3 on 2023-05-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0016_alter_products_rat_alter_products_prev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Rat',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pRev',
        ),
    ]
