# Generated by Django 4.1.3 on 2023-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0017_remove_products_rat_remove_products_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Rat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pRev',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
