# Generated by Django 4.1.3 on 2023-05-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppApp', '0019_alter_registration_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
    ]
